### ISSUE TITLE
Resnet50 from keras applications 

### ISSUE THREAD

**Issue by srihari-humbarwadi** [Attila94/refinenet-keras#1]
Can the resnet50 provided in keras applications be used as the backbone?

**Comment by Attila94** [comment]
Resnet50 is currently not supported but should be implementable. Unfortunately I don't have the time to look into this atm, but please feel free to give it a try if you feel like it.

**Comment by srihari-humbarwadi** [comment]
Just a quick question, the resnet feature maps that are used in the refinenet model are the outputs from the  relu activation layers of the respective residual blocks right?

**Comment by Attila94** [comment]
Sorry for the late reply but yes, that's correct.
