### ISSUE TITLE
error during run inference.py

### ISSUE THREAD

**Issue by ssxlconch** [Attila94/refinenet-keras#3]
sorry for bothering,
I downloaded the h5 file and run inference.py
but I suffered a ValueError

ValueError: You are trying to load a weight file containing 360 layers into a model with 393 layers.

Can you help me?

**Comment by Attila94** [comment]
You're right, I've updated the network architecture a while ago but did not upload the new weights, I'll fix it asap.

**Comment by ssxlconch** [comment]
Thanks for reply, could you please inform me if you had upload the new weights?

**Comment by Attila94** [comment]
Sorry for the late reply, have been looking for the correct weights file but I'm afraid I forgot to back it up and now it's gone forever... I guess your best option is to train your own RefineNet. Good luck!
