### ISSUE TITLE
Confusion in the weights file

### ISSUE THREAD

**Issue by marisna** [Attila94/refinenet-keras#8]
Hi, 

Thank you for sharing your work. 
Sorry to bother you, as I see no issues related to my error, I assume the error is mine. 
After severals tries to fix it, I think I rather ask it. 

I'm facing a recurrent issue between the weights files for pre-trained model. 

`ValueError: You are trying to load a weight file containing 304 layers into a model with 393 layers.`

(number 304 vary to 360 if i adress the refinenet weight filepath, either refinenet_baseline.hdf5 or weights.35-0.14.hdf5).
 
In your readme.md/Inference you mention: 
_"Specify paths to resnet101_weights_tf.h5, RefineNet weights file and your dataset base in inference.py"_ 
I see here only one path to adjust : 'weights', with no distinction between resnet's weights and refinenet's ones 
I had a look to your commit history, and saw that you modified your weights vars, precedently distinguished for resnet and refinenet. Even by looking close to your code, I'm not able to find the solution.   

Could you explicitly tell me which filepath have I to write in weights var in inference.py? 

Best,

**Comment by Attila94** [comment]
Sorry, that's my bad.

I noticed some mistakes in the model architecture and fixed them, but didn't upload a new weights file. You can try to checkout an earlier commit, the weights file should work fine with the old model.

**Comment by marisna** [comment]
Hi,

Thanks to answer me fast. I’ll follow your advice.

Best wishes for your work’s progresses !


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Attila Lengyel<mailto:notifications@github.com>
Envoyé le :jeudi 13 février 2020 10:23
À : Attila94/refinenet-keras<mailto:refinenet-keras@noreply.github.com>
Cc : marisna<mailto:marie-is@hotmail.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [Attila94/refinenet-keras] Confusion in the weights file (#8)


Sorry, that's my bad.

I noticed some mistakes in the model architecture and fixed them, but didn't upload a new weights file. You can try to checkout an earlier commit, the weights file should work fine with the old model.

**Comment by katrin1401** [comment]
Hi, with which commit does the refinenet_baseline.hdf5 work?

**Comment by Attila94** [comment]
This is the commit where I updated the architecture:
https://github.com/Attila94/refinenet-keras/commit/c03385fec5669e267990deea4d49ff1a28ae503a

So anything before that should be compatible.
